name: grocery_guardian
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  android_intent_plus: ^5.3.0
  shared_preferences: ^2.2.3
  http: ^1.4.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.2
  google_mobile_ads: ^6.0.0
  mobile_scanner: ^6.0.2
  flutter_secure_storage: ^9.2.2
  flutter_jailbreak_detection: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "icon.png"
